### ISSUE TITLE
Cover no longer thread-safe

### ISSUE THREAD

**Issue by jba** [google/licensecheck#16]
Previously, Cover could be invoked concurrently. Now (a18cfb0627bf), thanks to the shared state in Checker, it can't. 

The particular error I saw was "concurrent map read and map write", with one offender at normalize.go:57.

This isn't that important since checking is now a lot faster, but it still takes about 30s to run on about 29K licenses.

**Comment by jba** [comment]
I should add that this is a feature request, not a bug report: Cover never claimed to be thread-safe.

**Comment by rsc** [comment]
Will fix.
