### ISSUE TITLE
BSD-3-clause variants no longer match properly

### ISSUE THREAD

**Issue by jba** [google/licensecheck#17]
At 5cc4f616f8db, a BSD-3-Clause variant like https://github.com/d0ngw/cache/blob/v0.1.0/LICENSE no longer matches well (we are back to a split BSD-2/BSD-3). I think the difference is "names" in the license text vs. "name" in the template.

**Comment by jba** [comment]
Changing the relevant part of the template to
```
Neither ___ be used 
```
fixes many, but there are still three that don't match now but did before.

- https://github.com/lwes/lwes-go/blob/f32784a040b3887eebbd4a5f83d33916f12d0767/LICENSE, where clause 3 ends with "... permission of OpenX Technologies, Inc.", matches BSD-3 at 89.3.

- https://github.com/smallfish/rabbitmq-http/blob/master/LICENSE.md similarly ends in "permission of Mozilla Foundation" and matches at 89.2%.

- https://github.com/AndreyZWorkAccount/XIRR/blob/master/LICENSE changes clause 3 significantly. It may be better that we don't match it.

**Comment by rsc** [comment]
All fixed. Not worried about the change in AndreyZWorkAccount.
