### ISSUE TITLE
Support for bespoke open source licenses

### ISSUE THREAD

**Issue by tav** [google/licensecheck#18]
I use a bespoke open source license for all of my projects, e.g.

* https://github.com/dappui/core/blob/master/UNLICENSE.md

Unfortunately [pkg.go.dev](https://pkg.go.dev) refuses to display documentation since it's not on the pre-approved list of licenses. Is the recommended solution to host the documentation ourselves or to add the license to `licensecheck`?

**Comment by dsymonds** [comment]
You'd have to ask the pkg.go.dev folk what the recommended solution is. This package is only about license detection, not about policies for acting on those licenses.
