### ISSUE TITLE
Cover() returns {NaN, []} on text that only contains newlines.

### ISSUE THREAD

**Issue by kneep** [google/licensecheck#19]
Hi.
Thanks for this great library. I'm making a tool with it and happened to find this.

How to reproduce:
1. create an empty file or a file with only a newline in;
2. input the content of the file to Cover();
3. check the output.

Not sure if this is intended behavior. Seems like a bug.

**Comment by rsc** [comment]
The coverage of an empty file is 0 words matched / 0 words.
That's reported as NaN.
Should it be 0 instead? Or 100?
Hard to say.
The usual answer for 0/0 is NaN.

**Comment by robpike** [comment]
It's easy to add the if statement that turns 0/0 into 0. Seems more user-friendly.

**Comment by kneep** [comment]
> It's easy to add the if statement that turns 0/0 into 0. Seems more user-friendly.

Yes, returning a 0 is more user-friendly. What I'm doing is adding an if after Coverage() returns and replace the NaN because I need to output the result into a json file.
