### ISSUE TITLE
Dual license problems

### ISSUE THREAD

**Issue by gbbr** [google/licensecheck#22]
We have [a repository](https://github.com/DataDog/dd-trace-go) that is dual-licensed. I have followed the guidelines for file naming (`LICENSE-APACHE`, `LICENSE-BSD3`) but the package seems to be bothered by the standard [`LICENSE`](https://github.com/DataDog/dd-trace-go/blob/v1.23.0/LICENSE) file which specifies that the package is dual-licensed. What is the suggested way to fix this? There are two options:

* Modify this package to support the [SPDX header](https://en.wikipedia.org/wiki/Software_Package_Data_Exchange) that we have in our [LICENSE](https://github.com/DataDog/dd-trace-go/blob/v1.23.0/LICENSE) file.
* We remove the `LICENSE` file, leaving only the `LICENSE-APACHE` and `LICENSE-BSD3` files.

Please advise. It's quite unfortunate that users can't see [documentation](https://pkg.go.dev/gopkg.in/DataDog/dd-trace-go.v1/ddtrace?tab=doc).

**Comment by dsymonds** [comment]
This package doesn't make any decisions on files or filenames or the like. It identifies the licenses in a blob of bytes only. You need to report the issue to the pkg.go.dev site, since that's the place that is making decisions about files, etc.

**Comment by gbbr** [comment]
Right, didn't bother to look at the source. Thanks. I emailed go-discovery-feedback[att]google.com

**Comment by gbbr** [comment]
@dsymonds thinking about it more, this issue is actually about contents isn't it? Should this package not be able to identify the SPDX header in the contents and mark it as a dual license?

**Comment by rsc** [comment]
> I have followed the guidelines for file naming

What guidelines are those? I'm just curious.

**Comment by gbbr** [comment]
@rsc https://pkg.go.dev/license-policy

**Comment by gbbr** [comment]
@rsc why do you ask? Also just curious.

**Comment by rsc** [comment]
I was wondering whether we had explicitly said to write two different license files for dual-licensed code, which actually makes things harder for checking than just having one LICENSE file containing both. It looks like we have not said that.

The LICENSE file you have in your repo now is what I would have expected, not separate files.

We should revise that license-policy page to clarify best practices versus what we accept but would rather not see more of.
