### ISSUE TITLE
Add The Parity Public License 7.0.0

### ISSUE THREAD

**Issue by sudhirj** [google/licensecheck#23]
The Parity Public License is an offering from https://licensezero.com which acts as a licensing agency. 

SPDX: Parity-7.0.0 – https://spdx.org/licenses/Parity-7.0.0.html
Markdown: https://paritylicense.com/7.0.0.md
Online: https://paritylicense.com/versions/7.0.0

**Comment by sudhirj** [comment]
The .md file, which is what I expect should be added into the repo, is here 

https://paritylicense.com/7.0.0.md

**Comment by rsc** [comment]
I'd like to hold off on this until I've had some more time to work on the license checker engine proper. The more of these we add the trickier the corner cases get.
