### ISSUE TITLE
Add The Prosperity Public License 3.0.0

### ISSUE THREAD

**Issue by sudhirj** [google/licensecheck#24]
The Prosperity Public License is a noncommercial open source license offered by https://licensezero.com which is a commercial licensing agent. 

The full text of the license is here: 
https://prosperitylicense.com/versions/3.0.0

**Comment by sudhirj** [comment]
The .md file, which is what I expect should be added into the repo, is here

https://prosperitylicense.com/3.0.0.md

**Comment by rsc** [comment]
I'd like to hold off on this until I've had some more time to work on the license checker engine proper. The more of these we add the trickier the corner cases get.
