### ISSUE TITLE
Jurisdiction-ported Creative Commons license URLs are not recognised

### ISSUE THREAD

**Issue by kortschak** [google/licensecheck#4]
The CC BY 3.0 license (and possibly others?) have country coded ports indicated by a two-letter country code in the URL path. These are missed by license check. An example of this is the (old) license for [ajstarks/svgo](https://github.com/ajstarks/svgo/blob/de52242f3d65700ff4fa20a246fd17c8fcfc1d09/LICENSE#L1-L3):

```
The contents of this repository are Licensed under 
the Creative Commons Attribution 3.0 license as described in
http://creativecommons.org/licenses/by/3.0/us/
```

**Comment by ajstarks** [comment]
I agree.  I have now restored the original license (my attempt to appease go.dev failed).
