### ISSUE TITLE
Apache-2.0 URL alone is enough to match the license; is this intentional?

### ISSUE THREAD

**Issue by ericphanson** [google/licensecheck#40]
The Apache-2.0 URL (`http://www.apache.org/licenses/LICENSE-2.0`) alone counts as a match to the license. Text containing parts of other licenses usually does not produce a match, so I wanted to ask if this was intentional.

Here's the example using my Julia wrapper [LicenseCheck.jl](https://github.com/ericphanson/LicenseCheck.jl):
```julia
julia> using LicenseCheck

julia> licensecheck("http://www.apache.org/licenses/LICENSE-2.0")
(licenses_found = ["Apache-2.0"], license_file_percent_covered = 100.0)
```

**Comment by adg** [comment]
This is intentional. If the file is an 100% match for the Apache 2.0 URL then that is considered the license. If saw a `LICENSE` file in a repo that just contained that string, I'd infer the license was Apache 2.0.

**Comment by ericphanson** [comment]
Ah OK, good to know.

In case it's helpful, I found some other URLs don't get recognized:
```julia
julia> using LicenseCheck

julia> licensecheck("https://opensource.org/licenses/MIT")
(licenses_found = String[], license_file_percent_covered = 0.0)

julia> licensecheck("https://www.gnu.org/licenses/gpl-3.0.en.html")
(licenses_found = String[], license_file_percent_covered = 0.0)

julia> licensecheck("https://www.gnu.org/licenses/gpl-3.0.txt")
(licenses_found = String[], license_file_percent_covered = 0.0)

julia> licensecheck("https://www.apache.org/licenses/LICENSE-1.1")
(licenses_found = String[], license_file_percent_covered = 0.0)

```
