### ISSUE TITLE
AddMulan Permissive Software License v2 (MulanPSL - 2.0) ?

### ISSUE THREAD

**Issue by daqingshu** [google/licensecheck#46]
Please add https://opensource.org/licenses/MulanPSL-2.0 if possible.
To show MulanPSL-2.0 licensed go software on pkg.go.dev.
Eg. https://gitee.com/daqingshu/eurekaplugin

**Comment by jba** [comment]
That license is already present here. We have to add it to pkgsite. See golang/go#47613.
