### ISSUE TITLE
Variable sections are not considered in license descriptions

### ISSUE THREAD

**Issue by kortschak** [google/licensecheck#6]
The SPDX license descriptions (available [here](https://github.com/spdx/license-list-data)) include coding for sections of license that are variable (as described [here](https://spdx.org/spdx-license-list/matching-guidelines), with additional notes in the Matching Guidelines paragraph [here](https://spdx.org/spdx-license-list/license-list-overview)).

The absence of annotation of variable as opposed to required matching imposes the requirement for heuristic detection based on proportion of matching text, leading to both false positives with clearly incorrect classification of malicious license as OSS licenses and false negatives where perfect SPDX-match licenses are not correctly detected.

These issues have been raised at golang-dev and golang-nuts.

**Comment by robpike** [comment]
Yes, this is an issue with the way this library works that may require some redesign.

**Comment by jba** [comment]
I am not a lawyer and this is not legal advice, but my understanding is that there is a problem when an SPDX description is coupled with license text. If the two disagree, there is serious doubt that a short computer-readable token like `0BSD` would take precedence in a court's eyes over actual human-readable text like the full contents of the MIT license.

So I would hope that licensecheck doesn't try to interpret SPDX combined with license text.

If the SPDX description is on its own, then you wouldn't need this library anyway, just an SPDX parser.

**Comment by kortschak** [comment]
I am not talking about SPDX tokens, but rather the SPDX license descriptions, for example [this JSON](https://github.com/spdx/license-list-data/blob/master/json/details/BSD-3-Clause.json) for BSD 3 clause. This description shows which regions of the license text may be varied and which may not.
